SELECT loja,
       ni,
       nf,
       emissao,
       entrada,
       vendno,
       totalPrd,
       valorNF,
       carrno,
       carrName,
       cte,
       emissaoCte,
       entradaCte,
       valorCte,
       pesoBruto,
       cub,
       pesoCub,
       fPeso,
       adValore,
       gris,
       taxa,
       outro,
       aliquota,
       icms,
       totalFrete
FROM sqldados.queryCte1234567